### ISSUE TITLE
About the motion vector

### ISSUE THREAD

**Issue by JXH-SHU** [LukasBommes/mv-extractor#16]
Thank you so much for open-sourcing your code!  But I used the provided environment to print the motion vector directly and found that it is not complete, (There is no corresponding motion vector for some areas).  Looking forward to your reply!

**Comment by LukasBommes** [comment]
Hey JXH-SHU,
could you provide a screenshot of the motion vectors output by mv-extractor? Depending on the visual content it is normal that some motion vectors are close to zero and consequently not visible. Take a look at the title image in the readme. Many vectors are actually zero or close to zero.
It just means that the macro block associated to the motion vector hasn't moved since the last frame.

**Comment by JXH-SHU** [comment]
Thank you for your reply. I printed the motion vector and block division maps. I found that there is no motion vector where the motion is severe in the two images
![mv_arrow](https://user-images.githubusercontent.com/45163941/180913069-06fe2fb3-d32a-42e2-8038-1f8dd13e4935.png)
![mv_block](https://user-images.githubusercontent.com/45163941/180913079-4aeeeb93-ac98-4e0c-bf06-e66dda21eb12.png)
.

**Comment by LukasBommes** [comment]
Without seeing the entire sequence, I would say the motion vector field looks quite reasonable. The camera seems to tilt horizontally, which is why the entire background moves horizontally. The players probably move in such a way that they stay in the same location between the frames. Hence, the motion vectors are of small magnitude.

In any case, mv-extractor just extracts what is provided in the video. You can also try to transcode into MPEG-4. If you first split your videos into individual frames, you can encode them into an MPEG-4 video with the following command:
```
ffmpeg -y -r <f> -i %06d.jpg -c:v mpeg4 -vf 'pad=ceil(iw/2)*2:ceil(ih/2)*2' -f rawvideo out.mp4
```
(You can also transcode directly, but you'll have to figure out he exact ffmpeg command)

**Comment by JXH-SHU** [comment]
Thanks again for your reply. In fact, I also extract data from a mp4 video. Here, I added  three consecutive frames. What confuses me is that there is no corresponding optical flow in places with intense motion.
![img000084](https://user-images.githubusercontent.com/45163941/180973772-f70112af-2356-4cef-9af8-0cc659583425.png)
![img000085](https://user-images.githubusercontent.com/45163941/180973808-d6bff0f1-7182-4866-9af5-9a55be1cc2bf.png)
![img000086](https://user-images.githubusercontent.com/45163941/180973850-cab4311e-9ef4-422a-a4be-61926f11f527.png)

**Comment by LukasBommes** [comment]
To me, the motion vectors still look reasonable. At least in the three frames you posted above, there is not much motion around the players, whereas the entire background moves to the left.
However, I am not entirely sure, why the macroblock segmentation is not present in the area of the players.
