### ISSUE TITLE
Motion Vector Amount Consistency

### ISSUE THREAD

**Issue by elugo1** [LukasBommes/mv-extractor#35]
Hi! This tool is awesome and easy to use, for a project I am trying to extract the --dump motion vector values and turn them into polar coordinates for instancing in another project. It seems that for every frame though, I receive a different number of motion vectors. Is this normal? 
below is me unsorted, printing the number of lines in each motion vector .npy file. I am working with a 720p video and am expecting 3600 motion vectors based on the 16 x 16 kernel
![image](https://github.com/LukasBommes/mv-extractor/assets/82634063/8ddee650-8660-4972-b0d6-e5d7124f5bd5)

**Comment by LukasBommes** [comment]
Hey @elugo1,
yes, this is "normal" for MPEG-4 and H.264. The encoder may choose not to perform motion prediction on some macroblocks if the scene in the area of the macroblock did not change between consecutive frames.

If you run `extract_mvs vid_mpeg4_part2.mp4 --verbose` on the provided 720p MPEG-4 video you will see that the number of motion vectors is smaller or equal to 3600. For the H.264 encoded video provided in this repo, the number of motion vectors can be larger than 3600 because in H.264 macroblocks can be subdivided into subblocks (down to 4 x 4) for motion prediction. Each subblock will have an associated motion vector.
