### ISSUE TITLE
Install Size

### ISSUE THREAD

**Issue by dananomer** [LukasBommes/mv-extractor#5]
how much free space is required for the installation? it take considerable amount of time to install

**Comment by LukasBommes** [comment]
It takes long because I am downloading and building both OpenCV and FFMPEG from source. I am not sure if there is a more elegant way of getting the necessary header files without installing the full libraries.
About the size requirement I can not give you a specific value as I currently have no build of the project. The resulting Docker image should be a few GB, mostly due to the large size of the base image (Ubuntu 18.04). Since I am using multistage builds, the size is already reduced.

**Comment by dananomer** [comment]
Thank you for your response
